import { Team, City, Match, Venue, Event, User, League, SponsorSlot, Deal, BusinessAccount } from "./types"

// ─── Teams ────────────────────────────────────────────────────────────────────

export const mockTeams: Team[] = [
  { id: "eng", name: "England",      shortCode: "ENG", group: "A", flagEmoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
  { id: "bra", name: "Brazil",       shortCode: "BRA", group: "A", flagEmoji: "🇧🇷" },
  { id: "fra", name: "France",       shortCode: "FRA", group: "B", flagEmoji: "🇫🇷" },
  { id: "arg", name: "Argentina",    shortCode: "ARG", group: "B", flagEmoji: "🇦🇷" },
  { id: "esp", name: "Spain",        shortCode: "ESP", group: "C", flagEmoji: "🇪🇸" },
  { id: "ger", name: "Germany",      shortCode: "GER", group: "C", flagEmoji: "🇩🇪" },
  { id: "por", name: "Portugal",     shortCode: "POR", group: "D", flagEmoji: "🇵🇹" },
  { id: "ned", name: "Netherlands",  shortCode: "NED", group: "D", flagEmoji: "🇳🇱" },
  { id: "usa", name: "USA",          shortCode: "USA", group: "E", flagEmoji: "🇺🇸" },
  { id: "mex", name: "Mexico",       shortCode: "MEX", group: "E", flagEmoji: "🇲🇽" },
  { id: "can", name: "Canada",       shortCode: "CAN", group: "F", flagEmoji: "🇨🇦" },
  { id: "jpn", name: "Japan",        shortCode: "JPN", group: "F", flagEmoji: "🇯🇵" },
  { id: "mar", name: "Morocco",      shortCode: "MAR", group: "G", flagEmoji: "🇲🇦" },
  { id: "sen", name: "Senegal",      shortCode: "SEN", group: "G", flagEmoji: "🇸🇳" },
  { id: "aus", name: "Australia",    shortCode: "AUS", group: "H", flagEmoji: "🇦🇺" },
  { id: "ksa", name: "Saudi Arabia", shortCode: "KSA", group: "H", flagEmoji: "🇸🇦" },
]

// Helper to get a team by id
function team(id: string): Team {
  const t = mockTeams.find(t => t.id === id)
  if (!t) throw new Error(`Team not found: ${id}`)
  return t
}

// ─── Cities ───────────────────────────────────────────────────────────────────

export const mockCities: City[] = [
  { id: "nyc",  name: "New York / New Jersey", country: "USA",    timezone: "America/New_York",    venueCount: 12 },
  { id: "lax",  name: "Los Angeles",           country: "USA",    timezone: "America/Los_Angeles", venueCount: 9  },
  { id: "dal",  name: "Dallas",                country: "USA",    timezone: "America/Chicago",     venueCount: 7  },
  { id: "mia",  name: "Miami",                 country: "USA",    timezone: "America/New_York",    venueCount: 8  },
  { id: "atl",  name: "Atlanta",               country: "USA",    timezone: "America/New_York",    venueCount: 6  },
  { id: "sea",  name: "Seattle",               country: "USA",    timezone: "America/Los_Angeles", venueCount: 5  },
  { id: "tor",  name: "Toronto",               country: "Canada", timezone: "America/Toronto",     venueCount: 8  },
  { id: "gdl",  name: "Guadalajara",           country: "Mexico", timezone: "America/Monterrey",   venueCount: 6  },
]

// ─── Matches ──────────────────────────────────────────────────────────────────

export const mockMatches: Match[] = [
  {
    id: "m01",
    homeTeam: team("usa"),
    awayTeam: team("mex"),
    kickoffTime: "2026-06-12T18:00:00Z",
    stadium: "MetLife Stadium",
    city: "New York / New Jersey",
    cityId: "nyc",
    stage: "Group Stage",
    status: "upcoming",
  },
  {
    id: "m02",
    homeTeam: team("eng"),
    awayTeam: team("bra"),
    kickoffTime: "2026-06-13T21:00:00Z",
    stadium: "SoFi Stadium",
    city: "Los Angeles",
    cityId: "lax",
    stage: "Group Stage",
    status: "upcoming",
  },
  {
    id: "m03",
    homeTeam: team("fra"),
    awayTeam: team("arg"),
    kickoffTime: "2026-06-14T18:00:00Z",
    stadium: "AT&T Stadium",
    city: "Dallas",
    cityId: "dal",
    stage: "Group Stage",
    status: "upcoming",
  },
  {
    id: "m04",
    homeTeam: team("esp"),
    awayTeam: team("ger"),
    kickoffTime: "2026-06-15T21:00:00Z",
    stadium: "Hard Rock Stadium",
    city: "Miami",
    cityId: "mia",
    stage: "Group Stage",
    status: "upcoming",
  },
  {
    id: "m05",
    homeTeam: team("por"),
    awayTeam: team("ned"),
    kickoffTime: "2026-06-16T18:00:00Z",
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    cityId: "atl",
    stage: "Group Stage",
    status: "upcoming",
  },
  {
    id: "m06",
    homeTeam: team("can"),
    awayTeam: team("jpn"),
    kickoffTime: "2026-06-17T00:00:00Z",
    stadium: "BMO Field",
    city: "Toronto",
    cityId: "tor",
    stage: "Group Stage",
    status: "upcoming",
  },
  {
    id: "m07",
    homeTeam: team("mar"),
    awayTeam: team("sen"),
    kickoffTime: "2026-06-18T18:00:00Z",
    stadium: "Estadio Akron",
    city: "Guadalajara",
    cityId: "gdl",
    stage: "Group Stage",
    status: "upcoming",
  },
  {
    id: "m08",
    homeTeam: team("aus"),
    awayTeam: team("ksa"),
    kickoffTime: "2026-06-19T21:00:00Z",
    stadium: "Lumen Field",
    city: "Seattle",
    cityId: "sea",
    stage: "Group Stage",
    status: "upcoming",
  },
  {
    id: "m09",
    homeTeam: team("bra"),
    awayTeam: team("arg"),
    kickoffTime: "2026-06-26T21:00:00Z",
    stadium: "MetLife Stadium",
    city: "New York / New Jersey",
    cityId: "nyc",
    stage: "Group Stage",
    status: "upcoming",
  },
  {
    id: "m10",
    homeTeam: team("esp"),
    awayTeam: team("fra"),
    kickoffTime: "2026-06-27T18:00:00Z",
    stadium: "SoFi Stadium",
    city: "Los Angeles",
    cityId: "lax",
    stage: "Group Stage",
    status: "upcoming",
  },
  {
    id: "m11",
    homeTeam: team("eng"),
    awayTeam: team("ger"),
    kickoffTime: "2026-07-04T21:00:00Z",
    stadium: "AT&T Stadium",
    city: "Dallas",
    cityId: "dal",
    stage: "Round of 16",
    status: "upcoming",
  },
  {
    id: "m12",
    homeTeam: team("por"),
    awayTeam: team("usa"),
    kickoffTime: "2026-07-05T18:00:00Z",
    stadium: "Hard Rock Stadium",
    city: "Miami",
    cityId: "mia",
    stage: "Round of 16",
    status: "upcoming",
  },
]

// ─── Venues ───────────────────────────────────────────────────────────────────

export const mockVenues: Venue[] = [
  {
    id: "v01",
    name: "Legends Sports Bar",
    cityId: "nyc",
    city: "New York / New Jersey",
    address: "6 W 33rd St, New York, NY 10001",
    matchIds: ["m01", "m09"],
    price: "free",
    capacity: 300,
    featured: true,
    bigScreen: true,
    familyFriendly: false,
    foodAvailable: true,
    status: "approved",
    businessId: "biz01",
    views: 1240,
    clicks: 310,
    saves: 87,
    bookings: 54,
  },
  {
    id: "v02",
    name: "Rooftop Futbol Club",
    cityId: "nyc",
    city: "New York / New Jersey",
    address: "230 5th Ave Rooftop, New York, NY 10001",
    matchIds: ["m01", "m09"],
    price: "ticketed",
    capacity: 150,
    featured: true,
    bigScreen: true,
    familyFriendly: false,
    foodAvailable: true,
    status: "approved",
    businessId: "biz02",
    views: 980,
    clicks: 245,
    saves: 62,
    bookings: 41,
  },
  {
    id: "v03",
    name: "The Fox & Hound",
    cityId: "lax",
    city: "Los Angeles",
    address: "1735 Cahuenga Blvd, Hollywood, CA 90028",
    matchIds: ["m02", "m10"],
    price: "free",
    capacity: 200,
    featured: false,
    bigScreen: true,
    familyFriendly: true,
    foodAvailable: true,
    status: "approved",
    businessId: "biz03",
    views: 760,
    clicks: 190,
    saves: 43,
    bookings: 0,
  },
  {
    id: "v04",
    name: "Galaxy Fan Zone",
    cityId: "lax",
    city: "Los Angeles",
    address: "18400 Avalon Blvd, Carson, CA 90746",
    matchIds: ["m02", "m10"],
    price: "ticketed",
    capacity: 500,
    featured: true,
    bigScreen: true,
    familyFriendly: true,
    foodAvailable: true,
    status: "approved",
    businessId: "biz04",
    views: 2100,
    clicks: 630,
    saves: 175,
    bookings: 212,
  },
  {
    id: "v05",
    name: "Lone Star Fútbol Bar",
    cityId: "dal",
    city: "Dallas",
    address: "2624 Elm St, Dallas, TX 75226",
    matchIds: ["m03", "m11"],
    price: "free",
    capacity: 180,
    featured: false,
    bigScreen: true,
    familyFriendly: false,
    foodAvailable: true,
    status: "approved",
    businessId: "biz05",
    views: 540,
    clicks: 122,
    saves: 28,
    bookings: 0,
  },
  {
    id: "v06",
    name: "South Beach Soccer Social",
    cityId: "mia",
    city: "Miami",
    address: "1 Ocean Dr, Miami Beach, FL 33139",
    matchIds: ["m04", "m12"],
    price: "ticketed",
    capacity: 250,
    featured: true,
    bigScreen: true,
    familyFriendly: true,
    foodAvailable: true,
    status: "approved",
    businessId: "biz06",
    views: 1870,
    clicks: 560,
    saves: 143,
    bookings: 98,
  },
  {
    id: "v07",
    name: "The Maple Leaf Pub",
    cityId: "tor",
    city: "Toronto",
    address: "487 Church St, Toronto, ON M4Y 2C5",
    matchIds: ["m06"],
    price: "free",
    capacity: 120,
    featured: false,
    bigScreen: true,
    familyFriendly: false,
    foodAvailable: true,
    status: "approved",
    businessId: "biz07",
    views: 430,
    clicks: 95,
    saves: 22,
    bookings: 0,
  },
  {
    id: "v08",
    name: "Tequila & Goals",
    cityId: "gdl",
    city: "Guadalajara",
    address: "Av. Vallarta 2440, Guadalajara, Jalisco",
    matchIds: ["m07"],
    price: "free",
    capacity: 220,
    featured: false,
    bigScreen: true,
    familyFriendly: true,
    foodAvailable: true,
    status: "approved",
    businessId: "biz08",
    views: 680,
    clicks: 167,
    saves: 51,
    bookings: 0,
  },
  {
    id: "v09",
    name: "Downtown Fan Hall",
    cityId: "atl",
    city: "Atlanta",
    address: "Demo submission - address pending verification",
    matchIds: ["m05"],
    price: "free",
    capacity: 160,
    featured: false,
    bigScreen: true,
    familyFriendly: true,
    foodAvailable: true,
    status: "pending",
    businessId: "biz09",
    views: 0,
    clicks: 0,
    saves: 0,
    bookings: 0,
  },
]

// ─── Events ───────────────────────────────────────────────────────────────────

export const mockEvents: Event[] = [
  {
    id: "e01",
    venueId: "v01",
    name: "USA vs Mexico Watch Party",
    matchId: "m01",
    date: "2026-06-12T17:00:00Z",
    description: "Join us for the biggest rivalry in CONCACAF! Drink specials all night, half-time giveaways, and a DJ set after the final whistle.",
    status: "approved",
  },
  {
    id: "e02",
    venueId: "v04",
    name: "England vs Brazil Fan Experience",
    matchId: "m02",
    date: "2026-06-13T19:30:00Z",
    description: "Official Galaxy Fan Zone presents the Three Lions vs Seleção. Giant screens, food trucks, face painting for kids, and exclusive merch bundles.",
    status: "approved",
  },
  {
    id: "e03",
    venueId: "v06",
    name: "South Beach La Liga Fiesta",
    matchId: "m04",
    date: "2026-06-15T20:00:00Z",
    description: "Spain vs Germany under the Miami stars. Rooftop pool access, premium cocktail packages, and live entertainment before kick-off.",
    status: "approved",
  },
  {
    id: "e04",
    venueId: "v07",
    name: "Canada World Cup Night",
    matchId: "m06",
    date: "2026-06-16T22:30:00Z",
    description: "Support the home nation at Toronto's most beloved football pub. Poutine specials, Canadian craft beers, and a massive prize draw at full time.",
    status: "approved",
  },
  {
    id: "e05",
    venueId: "v09",
    name: "Atlanta Group Stage Watch Party",
    matchId: "m05",
    date: "2026-06-16T16:30:00Z",
    description: "Demo event submission awaiting admin review.",
    status: "pending",
  },
]

// ─── Business Accounts ───────────────────────────────────────────────────────

export const mockBusinessAccounts: BusinessAccount[] = [
  {
    id: "biz01",
    name: "Legends Sports Bar",
    email: "owner@example.com",
    venueIds: ["v01"],
    plan: "featured",
    status: "active",
  },
  {
    id: "biz09",
    name: "Downtown Fan Hall",
    email: "pending@example.com",
    venueIds: ["v09"],
    plan: "free",
    status: "pending",
  },
]

// ─── Users & Predictions ──────────────────────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: "u01",
    name: "Alex Rivera",
    email: "alex.rivera@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
    favouriteTeams: ["usa", "mex"],
    cityId: "nyc",
    interests: ["Group Stage", "Round of 16"],
    savedVenues: ["v01", "v02"],
    savedMatches: ["m01", "m09", "m12"],
    points: 27,
    predictions: [
      { id: "p01", userId: "u01", matchId: "m01", homeScore: 2, awayScore: 1, points: 2 },
      { id: "p02", userId: "u01", matchId: "m09", homeScore: 3, awayScore: 2, points: 2 },
      { id: "p03", userId: "u01", matchId: "m02", homeScore: 1, awayScore: 1, points: 5 },
      { id: "p04", userId: "u01", matchId: "m11", homeScore: 2, awayScore: 0, points: 0 },
      { id: "p05", userId: "u01", matchId: "m12", homeScore: 1, awayScore: 2, points: 0 },
    ],
    badges: ["First Prediction", "Matchday Regular", "Venue Explorer", "Correct Score", "Super Fan"],
  },
  {
    id: "u02",
    name: "Priya Patel",
    email: "priya.patel@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=priya",
    favouriteTeams: ["eng", "ind"],
    cityId: "lax",
    interests: ["Group Stage"],
    savedVenues: ["v03", "v04"],
    savedMatches: ["m02", "m10"],
    points: 12,
    predictions: [
      { id: "p06", userId: "u02", matchId: "m02", homeScore: 2, awayScore: 0, points: 2 },
      { id: "p07", userId: "u02", matchId: "m10", homeScore: 1, awayScore: 1, points: 0 },
    ],
    badges: ["First Prediction", "Venue Explorer"],
  },
  {
    id: "u03",
    name: "Carlos Mendez",
    email: "carlos.mendez@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=carlos",
    favouriteTeams: ["mex", "arg"],
    cityId: "dal",
    interests: ["Group Stage", "Round of 16"],
    savedVenues: ["v05"],
    savedMatches: ["m03", "m07", "m11"],
    points: 19,
    predictions: [
      { id: "p08", userId: "u03", matchId: "m03", homeScore: 1, awayScore: 2, points: 2 },
      { id: "p09", userId: "u03", matchId: "m07", homeScore: 2, awayScore: 1, points: 5 },
      { id: "p10", userId: "u03", matchId: "m11", homeScore: 0, awayScore: 1, points: 2 },
    ],
    badges: ["First Prediction", "Matchday Regular", "Correct Score"],
  },
  {
    id: "u04",
    name: "Sophie Laurent",
    email: "sophie.laurent@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sophie",
    favouriteTeams: ["fra", "esp"],
    cityId: "mia",
    interests: ["Group Stage"],
    savedVenues: ["v06"],
    savedMatches: ["m03", "m04"],
    points: 7,
    predictions: [
      { id: "p11", userId: "u04", matchId: "m03", homeScore: 3, awayScore: 1, points: 2 },
      { id: "p12", userId: "u04", matchId: "m04", homeScore: 2, awayScore: 2, points: 0 },
    ],
    badges: ["First Prediction"],
  },
  {
    id: "u05",
    name: "Liam O'Brien",
    email: "liam.obrien@example.com",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=liam",
    favouriteTeams: ["eng", "por"],
    cityId: "tor",
    interests: ["Group Stage", "Round of 16"],
    savedVenues: ["v07"],
    savedMatches: ["m02", "m05", "m11", "m12"],
    points: 15,
    predictions: [
      { id: "p13", userId: "u05", matchId: "m02", homeScore: 1, awayScore: 0, points: 2 },
      { id: "p14", userId: "u05", matchId: "m05", homeScore: 2, awayScore: 1, points: 2 },
      { id: "p15", userId: "u05", matchId: "m11", homeScore: 1, awayScore: 0, points: 5 },
    ],
    badges: ["First Prediction", "Matchday Regular", "Correct Score"],
  },
]

// Convenience export for demo/current user
export const currentUser: User = mockUsers[0]

// ─── Leagues ──────────────────────────────────────────────────────────────────

export const mockLeagues: League[] = [
  {
    id: "l01",
    name: "Office World Cup Bracket",
    code: "OWC2026",
    creatorId: "u01",
    memberIds: ["u01", "u02", "u03", "u04", "u05"],
    sponsored: false,
  },
  {
    id: "l02",
    name: "FanRush Pro League",
    code: "FRPRO26",
    creatorId: "u03",
    memberIds: ["u01", "u03", "u05"],
    sponsored: true,
  },
]

// ─── Sponsor Slots ────────────────────────────────────────────────────────────

export const mockSponsorSlots: SponsorSlot[] = [
  {
    id: "s01",
    name: "Coca-Cola Fan Zone Banner",
    type: "banner",
    active: true,
  },
  {
    id: "s02",
    name: "Adidas City Spotlight — New York",
    type: "city",
    active: true,
  },
]

// ─── Deals ────────────────────────────────────────────────────────────────────

export const mockDeals: Deal[] = [
  {
    id: "d01",
    title: "15% Off Match Day Tacos",
    description: "Flash your FanRush app at Lone Star Fútbol Bar and get 15% off the full food menu on any match day.",
    discount: "15%",
    venueId: "v05",
    cityId: "dal",
    category: "food",
  },
  {
    id: "d02",
    title: "Fly to New York from $79",
    description: "Spirit Airlines flash deal — book before June 10 and fly to Newark for the opening group stage matches.",
    discount: "From $79",
    cityId: "nyc",
    category: "travel",
  },
  {
    id: "d03",
    title: "Official England Replica Kit — 20% Off",
    description: "Nike official store discount for FanRush users. Use code FANRUSH20 at checkout.",
    discount: "20%",
    category: "merch",
  },
  {
    id: "d04",
    title: "Miami Airbnb Match Week Stays",
    description: "Save up to 12% on Airbnb properties in Miami Beach for the Spain vs Germany match week.",
    discount: "Up to 12%",
    cityId: "mia",
    category: "accommodation",
  },
  {
    id: "d05",
    title: "2-for-1 Burgers at Fox & Hound",
    description: "Show your FanRush profile and get a free burger with every burger purchased on match days.",
    discount: "2-for-1",
    venueId: "v03",
    cityId: "lax",
    category: "food",
  },
  {
    id: "d06",
    title: "World Cup 2026 Scarf Bundle",
    description: "Buy any 3 national team scarves from FanStore and get the cheapest one free. Ships worldwide.",
    discount: "Buy 2 Get 1 Free",
    category: "merch",
  },
]
